// The Finnish written into the app's screens: button labels, game titles,
// prompts ("Mitä kuulit?", "Lämmittely tehty!"). The child reads these as much
// as any lesson, so the native review must cover them too. They live inline in
// the components, so this pulls them out of the sources with the TypeScript
// parser:
//
//   • JSX text before an English span — `Jatka <span className="en">Continue</span>`;
//   • "Finnish · English" strings — `title="Kenen? · Whose?"`;
//   • `fi` / `titleFi` / `prompt` props and object fields, with their English partner;
//   • any other string a person reads that is Finnish, e.g. `'Valmis!'`.
//
// Finnish vs English is decided word by word: the Finnish lexicon (vendored
// Wiktionary forms) against the English one (vendored AGID + small words).
//
// `npm run review:content` writes the result to data/ui-finnish.json (read by
// game/reviewEntries.ts); a test re-extracts and fails if that file is out
// of date, so a new label can't skip the review. Test/script-only (node fs).

import ts from 'typescript';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { finnishLexicon, knownForm, wordsOf } from './finnishLexicon';

const SRC = join(__dirname, '..');
const AGID = join(SRC, '..', 'data', 'english-agid', 'infl.txt');

export const UI_FINNISH_README =
  "Generated by `npm run review:content` (src/test/uiFinnish.ts) — don't edit by hand. The Finnish in the app's screens (labels, game titles, prompts), for the native review: Grown-ups → Finnish check lists each under the key `ui:<the Finnish>`.";

export interface UiLabel {
  /** The Finnish as the child reads it; ⟨…⟩ is a value the app fills in. */
  fi: string;
  /** The English shown with it ('' when the screen shows none). */
  en: string;
  /** Source files it appears in (relative to src/). */
  where: string[];
}

/** The component sources: every screen and game, and the app shell. */
export function uiSourceFiles(): string[] {
  const components = readdirSync(join(SRC, 'components'))
    .filter((f) => f.endsWith('.tsx') && !f.includes('.test.'))
    .map((f) => `components/${f}`);
  return [...components, 'App.tsx'].sort();
}

/** Small English words AGID doesn't list (it lists words that inflect). */
const ENGLISH_SMALL = [
  'a', 'an', 'the', 'and', 'or', 'but', 'of', 'to', 'in', 'on', 'at', 'by', 'for', 'with', 'from', 'into', 'onto',
  'it', 'its', "it's", 'is', 'are', 'am', 'be', 'me', 'my', 'you', 'your', "you're", 'we', 'our', 'us', 'they',
  'them', 'their', 'he', 'she', 'him', 'his', 'her', 'this', 'that', 'these', 'those', 'all', 'some', 'any', 'no',
  'not', 'yes', 'ok', 'hi', 'up', 'out', 'off', 'so', 'as', 'if', 'then', 'than', 'too', 'very', 'just', 'here',
  'there', 'what', 'which', 'who', 'whose', 'how', 'why', 'when', 'where', "let's", "don't", "can't", "i'm", 'i',
  'more', 'most', 'each', 'every', 'again', 'now', 'only', 'also', 'one', 'first', 'next', 'last',
];

let english: Set<string> | null = null;

/** English word forms: AGID's common words and their inflections, plus the small words. */
export function englishWords(): Set<string> {
  if (english) return english;
  const set = new Set(ENGLISH_SMALL);
  for (const line of readFileSync(AGID, 'utf8').split('\n')) {
    // Lowercase headwords only (skips names and abbreviations like "EI").
    const m = line.match(/^([a-z][a-z'-]*) [A-Z]\??: (.*)$/);
    if (!m) continue;
    set.add(m[1]);
    for (const part of m[2].split(/[|,]/)) {
      const w = part.trim().split(/\s/)[0].replace(/[~<!?{}:\d]+/g, '');
      if (/^[a-z][a-z'-]*$/.test(w)) set.add(w);
    }
  }
  english = set;
  return set;
}

/** A word the lexicon knows, as itself or as a two-part compound (väli + testi). */
export function knownOrCompound(word: string, lexicon = finnishLexicon()): boolean {
  if (knownForm(word, lexicon)) return true;
  const w = word.toLowerCase();
  for (let i = 3; i <= w.length - 3; i++) {
    if (lexicon.has(w.slice(0, i)) && knownForm(w.slice(i), lexicon)) return true;
  }
  return false;
}

const withoutSlots = (s: string) => s.replace(/⟨[^⟩]*⟩/g, ' ');

export type Lang = 'fi' | 'en' | 'unsure' | 'none';

/**
 * Which language a bit of text is in, by majority: words only Finnish know
 * against words only English knows (words in both — "on", "show", "bonus" —
 * don't vote). 'unsure' when neither side wins (e.g. a Finnish word the
 * vendored tables lack, like "Kertaus"); 'none' if it has no words.
 */
export function langOf(text: string, lexicon = finnishLexicon(), en = englishWords()): Lang {
  const words = wordsOf(withoutSlots(text))
    .map((w) => w.toLowerCase())
    .filter((w) => w.length >= 2);
  if (words.length === 0) return 'none';
  let fi = 0;
  let english = 0;
  let unknown = 0;
  for (const w of words) {
    const isFi = /[äöå]/.test(w) || knownOrCompound(w, lexicon);
    const isEn = en.has(w);
    if (isFi && !isEn) fi++;
    else if (isEn && !isFi) english++;
    else if (!isFi && !isEn) unknown++;
  }
  if (fi > english) return 'fi';
  if (english > fi) return 'en';
  // Only words both languages share ("Show", "Avatar"): read as the English UI.
  if (fi === 0 && unknown === 0) return 'en';
  return 'unsure';
}

/** Trim emoji, arrows and spacing from the edges; keep the words and their punctuation. */
function clean(s: string): string {
  return s
    .replace(/\s+/g, ' ')
    .replace(/^[^\p{L}\p{N}⟨"'«(¿¡]+/u, '')
    .replace(/[^\p{L}\p{N}⟩?!.…"'»)]+$/u, '')
    .trim();
}

/**
 * Looks like a label a person reads — capitalized, with a real word in it —
 * not a code value ('warmup'), an abbreviation ('Mo') or camelCase.
 */
const labelLike = (s: string) =>
  /^[A-ZÅÄÖ⟨]/.test(s) &&
  !/[_/=<>{}\\]|[a-zåäö][A-ZÅÄÖ]|\w\.\w/.test(s) &&
  /[\p{L}]{4,}/u.test(withoutSlots(s));

/** A JSX expression as the reader sees it: a literal's text, else ⟨name⟩ / ⟨…⟩. */
function shown(expr: ts.Expression | undefined, inTemplate = false): string {
  if (!expr) return '';
  if (ts.isStringLiteral(expr) || ts.isNoSubstitutionTemplateLiteral(expr)) return expr.text;
  if (ts.isIdentifier(expr)) return `⟨${expr.text}⟩`;
  if (ts.isPropertyAccessExpression(expr)) return `⟨${expr.name.text}⟩`;
  if (ts.isParenthesizedExpression(expr)) return shown(expr.expression, inTemplate);
  // In a template, `${ok ? 'Kyllä' : 'Ei'}` reads as ⟨Kyllä / Ei⟩.
  if (
    inTemplate &&
    ts.isConditionalExpression(expr) &&
    ts.isStringLiteral(expr.whenTrue) &&
    ts.isStringLiteral(expr.whenFalse) &&
    expr.whenTrue.text &&
    expr.whenFalse.text
  ) {
    return `⟨${expr.whenTrue.text} / ${expr.whenFalse.text}⟩`;
  }
  return '⟨…⟩';
}

/** A template literal with its `${…}` parts as ⟨…⟩. */
function templateText(t: ts.TemplateExpression): string {
  return t.head.text + t.templateSpans.map((s) => shown(s.expression, true) + s.literal.text).join('');
}

const isEnSpan = (el: ts.JsxElement) =>
  el.openingElement.tagName.getText() === 'span' &&
  el.openingElement.attributes.properties.some(
    (a) =>
      ts.isJsxAttribute(a) &&
      a.name.getText() === 'className' &&
      !!a.initializer &&
      ts.isStringLiteral(a.initializer) &&
      a.initializer.text.split(/\s+/).includes('en'),
  );

/** The plain text of some JSX children (for the English span). */
function childrenText(children: ts.NodeArray<ts.JsxChild>): string {
  return children
    .map((c) => (ts.isJsxText(c) ? c.text : ts.isJsxExpression(c) ? shown(c.expression) : ''))
    .join('');
}

/** Attributes no person reads. */
const CODE_ATTRS = new Set([
  'className', 'to', 'href', 'path', 'key', 'id', 'lang', 'type', 'inputMode', 'autoComplete', 'role', 'src',
  'accept', 'name', 'htmlFor', 'state', 'element', 'style', 'mode', 'kind', 'variant', 'size', 'activity',
]);
/** Finnish field → its English partner, on props and object literals. */
const PAIRS: Record<string, string[]> = {
  fi: ['en', 'label', 'aria-label'],
  titleFi: ['titleEn'],
  prompt: ['promptEn'],
  promptFi: ['promptEn'],
  labelFi: ['labelEn'],
  nameFi: ['nameEn'],
};

const isText = (n: ts.Node | undefined): n is ts.StringLiteral | ts.NoSubstitutionTemplateLiteral =>
  !!n && (ts.isStringLiteral(n) || ts.isNoSubstitutionTemplateLiteral(n));

export function extractUiFinnish(files = uiSourceFiles(), lexicon = finnishLexicon(), en = englishWords()): UiLabel[] {
  const found = new Map<string, { en: Set<string>; where: Set<string> }>();
  const lang = (s: string) => langOf(s, lexicon, en);

  const put = (fi: string, gloss: string, file: string) => {
    const entry = found.get(fi) ?? { en: new Set<string>(), where: new Set<string>() };
    const g = clean(gloss.split(' · ')[0]);
    if (g && lang(g) !== 'fi') entry.en.add(g);
    entry.where.add(file);
    found.set(fi, entry);
  };
  /** A Finnish text with its English partner (the field / span says which is which). */
  const paired = (fiRaw: string, gloss: string, file: string) => {
    const fi = clean(fiRaw);
    const l = lang(fi);
    if (l === 'fi' || l === 'unsure') put(fi, gloss, file);
  };
  /** A string on its own: "Fi · En" splits; else sentence by sentence ("Muistatko? Remember?"). */
  const lone = (text: string, file: string) => {
    const parts = text.split(' · ');
    if (parts.length === 2 && lang(clean(parts[0])) !== 'en' && lang(clean(parts[1])) === 'en') {
      paired(parts[0], parts[1], file);
      return;
    }
    for (const part of parts) {
      // English prose (even with a Finnish word in it), and example placeholders.
      if (lang(part) === 'en' || /^e\.g\./.test(part.trim())) continue;
      const chunks = clean(part).split(/(?<=[?!.…])\s+/);
      for (let i = 0; i < chunks.length; i++) {
        const c = clean(chunks[i]);
        const l = lang(c);
        if (l !== 'fi' && !(l === 'unsure' && labelLike(c))) continue;
        let gloss = '';
        for (let j = i + 1; j < chunks.length && lang(chunks[j]) === 'en'; j++) gloss += (gloss ? ' ' : '') + chunks[j];
        put(c, gloss, file);
      }
    }
  };

  for (const file of files) {
    const text = readFileSync(join(SRC, file), 'utf8');
    const sf = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
    const handled = new Set<ts.Node>();
    const markAll = (n: ts.Node) => {
      handled.add(n);
      ts.forEachChild(n, markAll);
    };

    const visit = (node: ts.Node) => {
      // JSX children: runs of text, each ended by an English span (its gloss)
      // or by any other element. (An English span's own text is the gloss, not
      // a label — but strings inside it are still swept: 'Muistatko? Remember?'.)
      if ((ts.isJsxElement(node) && !isEnSpan(node)) || ts.isJsxFragment(node)) {
        let run = '';
        const flush = (gloss: string | null) => {
          if (run.trim()) {
            if (gloss === null) lone(run, file);
            else paired(run, gloss, file);
          }
          run = '';
        };
        for (const c of node.children) {
          if (ts.isJsxText(c)) run += c.text;
          else if (ts.isJsxExpression(c)) {
            run += shown(c.expression);
            if (isText(c.expression)) handled.add(c.expression);
          } else if (ts.isJsxElement(c) && isEnSpan(c)) {
            flush(childrenText(c.children));
          } else flush(null);
        }
        flush(null);
      }
      // Props: fi="…" with its English partner; attributes no one reads are skipped.
      if (ts.isJsxAttributes(node)) {
        const attrs = new Map<string, ts.JsxAttribute>();
        for (const a of node.properties) if (ts.isJsxAttribute(a)) attrs.set(a.name.getText(), a);
        for (const [name, a] of attrs) {
          const init = a.initializer;
          if (!init) continue;
          if (CODE_ATTRS.has(name)) {
            markAll(init);
            continue;
          }
          if (PAIRS[name] && ts.isStringLiteral(init)) {
            const partner = PAIRS[name].map((p) => attrs.get(p)?.initializer).find(isText);
            paired(init.text, partner?.text ?? '', file);
            handled.add(init);
          }
        }
      }
      // Object fields: { fi: 'Edistyminen', en: 'Progress' }.
      if (ts.isObjectLiteralExpression(node)) {
        const props = new Map<string, ts.Expression>();
        for (const p of node.properties) {
          if (ts.isPropertyAssignment(p) && (ts.isIdentifier(p.name) || ts.isStringLiteral(p.name))) {
            props.set(p.name.text, p.initializer);
          }
        }
        for (const [name, partners] of Object.entries(PAIRS)) {
          const v = props.get(name);
          if (!isText(v)) continue;
          const partner = partners.map((p) => props.get(p)).find(isText);
          paired(v.text, partner?.text ?? '', file);
          handled.add(v);
          if (partner) handled.add(partner);
        }
      }
      ts.forEachChild(node, visit);
    };
    visit(sf);

    // Every other string a person might read, kept if it reads as Finnish.
    const sweep = (node: ts.Node) => {
      if (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) return;
      if (!handled.has(node)) {
        if (isText(node)) {
          const parent = node.parent;
          const isKey = ts.isPropertyAssignment(parent) && parent.name === node;
          const isCase = ts.isCaseClause(parent);
          const isCompare =
            ts.isBinaryExpression(parent) &&
            [ts.SyntaxKind.EqualsEqualsEqualsToken, ts.SyntaxKind.ExclamationEqualsEqualsToken].includes(
              parent.operatorToken.kind,
            );
          const isIndex = ts.isElementAccessExpression(parent);
          if (!isKey && !isCase && !isCompare && !isIndex) lone(node.text, file);
        } else if (ts.isTemplateExpression(node)) {
          lone(templateText(node), file);
          return;
        }
      }
      ts.forEachChild(node, sweep);
    };
    sweep(sf);
  }

  return [...found.entries()]
    .map(([fi, { en: glosses, where }]) => ({ fi, en: [...glosses].sort().join(' / '), where: [...where].sort() }))
    .sort((a, b) => a.fi.localeCompare(b.fi, 'fi'));
}
