// Generates docs/LESSON_AUDIT.md: every lesson exactly as a child sees it —
// references resolved to the looked-up Finnish, the ending a lesson talks about
// in [brackets], every check with its right (✔) and wrong (✘) options — so a
// grown-up or a native speaker can review the lessons in one read.
//
// Run: npm run audit:lessons  (vite-node — imports the real TS content)
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { lessons, resolveRef, type LessonRef } from '../src/content/lessons';
import { PERSONS, verbForm } from '../src/content/types';
import { itemById } from '../src/content/lookup';
import { PATH } from '../src/game/path';

const out: string[] = [
  '# Lesson audit — every lesson as the child sees it',
  '',
  '_Generated by `npm run audit:lessons`. Re-run after content changes._',
  '',
  'Finnish comes from the sourced tables or vetted phrase lines; the ending a',
  'lesson is talking about is shown in [brackets]. ✔ marks the right answer of a',
  '"try it" question.',
];
const row = (ref: LessonRef) => {
  const x = resolveRef(ref, 'Aino');
  if (!x) return `⚠️ UNRESOLVED ${JSON.stringify(ref)}`;
  const marked = x.segments.map((s) => (s.mark ? `[${s.text}]` : s.text)).join('');
  return `${x.emoji ? x.emoji + ' ' : ''}${x.base ? x.base + ' → ' : ''}**${marked}**${x.en ? ' — ' + x.en : ''}`;
};
lessons.forEach((l) => {
  const unit = PATH.findIndex((u) => u.lessonId === l.id);
  out.push('', `## Unit ${unit + 1}: ${l.titleEn} (${l.titleFi}) ${l.emoji}`);
  l.cards.forEach((c, ci) => {
    out.push('', `### ${ci + 1}. ${c.title ?? (c.kind === 'check' ? 'Try it' : '')} _(${c.kind})_`, '');
    if ('text' in c && c.text) out.push(c.text, '');
    if (c.kind === 'examples') c.rows.forEach((r) => out.push(`- ${row(r)}`));
    if (c.kind === 'pairs') {
      for (const id of c.ids) {
        out.push(`- 🗣️ ${row({ line: id, part: 'prompt' })}  →  ↪️ ${row({ line: id, part: 'reply' })}`);
      }
    }
    if (c.kind === 'verbTable') {
      const v = itemById(c.verb)!;
      out.push(`_${v.fi} (${v.en}), ${c.tense} ${c.polarity}_`, '');
      for (const p of PERSONS) out.push(`- ${p.fi} ${verbForm(v, c.tense, c.polarity, p.id)}`);
    }
    if (c.kind === 'check') {
      out.push(`**Q:** ${c.question}`, '');
      if (c.listen) out.push(`🔊 plays: ${row(c.listen)}`, '');
      c.options.forEach((o) => out.push(`- ${o.correct ? '✔' : '✘'} ${o.ref ? row(o.ref) : o.text}`));
      out.push('', `_Explain:_ ${c.explain}`);
    }
  });
});

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, '..', 'docs', 'LESSON_AUDIT.md');
writeFileSync(target, out.join('\n') + '\n');
console.log(`Wrote ${target}`);
