// Generates docs/SENTENCE_AUDIT.md: EVERY sentence the game can build, for
// human (Finnish) review. Two sections:
//   1. Carrier phrases — every construction × every eligible word (the same
//      formFor + suitsSlot gate the round builders use), so a semantically
//      odd pairing shows up here before a child ever sees it.
//   2. Sentence templates — every template × every swappable candidate.
// Deterministic order, so re-runs diff cleanly as content grows.
//
// Run: npm run audit:sentences  (vite-node — imports the real TS content)
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  animals,
  food,
  family,
  places,
  body,
  nature,
  clothes,
  verbs,
  adjectives,
  numbers,
  formFor,
  suitsSlot,
  sentenceFor,
} from '../src/content';
import { nounConstructions } from '../src/content/constructions';
import { sentenceConstructions } from '../src/content/sentences';
import type { SentenceConstruction } from '../src/content/types';
import { resolveSentence, type SentencePools } from '../src/game/round';

const NOUNS = [
  ...animals.items,
  ...food.items,
  ...family.items,
  ...places.items,
  ...body.items,
  ...nature.items,
  ...clothes.items,
];

const POOLS: SentencePools = {
  nouns: NOUNS,
  verbs: verbs.items,
  adjectives: adjectives.items,
  numbers: numbers.items,
};

const lines: string[] = [
  '# Sentence audit — every line the game can generate',
  '',
  '_Generated by `npm run audit:sentences`. Re-run after content changes._',
  '',
  'Review the Finnish below; fix oddities by tightening a construction\'s',
  '`topics`/`excludeIds` gate (src/content/constructions.ts) or a template\'s',
  '`pickFrom` set (src/content/sentences.ts), then regenerate.',
  '',
  '## 1. Carrier phrases (construction × eligible words)',
  '',
];

for (const con of nounConstructions) {
  const eligible = NOUNS.filter((i) => formFor(i, con) && suitsSlot(i, con)).sort((a, b) =>
    a.id.localeCompare(b.id),
  );
  const excluded = NOUNS.filter((i) => formFor(i, con) && !suitsSlot(i, con)).sort((a, b) =>
    a.id.localeCompare(b.id),
  );
  lines.push(
    `### \`${con.id}\` — “${con.en}” (tier ${con.tier}, ${con.case} ${con.number}, ${eligible.length} words)`,
    '',
  );
  for (const item of eligible) {
    lines.push(`- ${sentenceFor(item, con)} _(${item.en})_`);
  }
  if (excluded.length > 0) {
    lines.push('', `Gated out: ${excluded.map((i) => i.id).join(', ')}`);
  }
  lines.push('');
}

lines.push('## 2. Sentence templates (template × swappable candidates)', '');

/** Enumerate a template's swap slots (pickFrom, no fixedId) as fixed variants. */
function variants(template: SentenceConstruction): SentenceConstruction[] {
  let out: SentenceConstruction[] = [template];
  for (const slot of template.slots) {
    if (slot.fixedId || !slot.pickFrom || slot.pickFrom.length === 0) continue;
    const next: SentenceConstruction[] = [];
    for (const t of out) {
      for (const id of slot.pickFrom) {
        next.push({
          ...t,
          slots: t.slots.map((s) => (s.id === slot.id ? { ...s, fixedId: id } : s)),
        });
      }
    }
    out = next;
  }
  return out;
}

for (const template of sentenceConstructions) {
  lines.push(`### \`${template.id}\` — “${template.en}” (tier ${template.tier})`, '');
  for (const v of variants(template)) {
    const resolved = resolveSentence(v, POOLS);
    if (!resolved) {
      lines.push(`- ⚠️ UNRESOLVABLE variant (check slot forms): ${JSON.stringify(v.slots)}`);
      continue;
    }
    lines.push(`- ${resolved.words.join(' ')}${template.punct ?? ''} _(${resolved.gloss})_`);
  }
  lines.push('');
}

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'docs', 'SENTENCE_AUDIT.md');
writeFileSync(out, lines.join('\n') + '\n');
console.log(`Wrote ${out}`);
